AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
    PrefixLetters:
        Type: String
        Default: prod
    ProjectCode:
        Type: String
        Default: CS2P_PROD1

Globals:
    Function:
        Runtime: nodejs18.x
        Timeout: 10
        Handler: app.lambdaHandler

Resources:
    #_____FUNCTIONS_____
    #Entry
    # GetEntriesFunction:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         FunctionName: !Sub "${PrefixLetters}_${ProjectCode}_GetEntries"
    #         CodeUri: src/entry/getEntries
    
    GetEntryByIdFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "${PrefixLetters}_${ProjectCode}_GetEntryById"
            CodeUri: src/entry/getEntryById

    #_____INIT GRAPHQL_____
    GraphQLApi:
        Type: AWS::Serverless::GraphQLApi
        Properties:
            SchemaUri: ./gql/schema.graphql
            Name: !Sub "${PrefixLetters}_${ProjectCode}_GraphQL"
            Auth:
                Type: OPENID_CONNECT
                OpenIDConnect:
                    ClientId: "AkNRE1qjj3nSef4AjwItuL4NrtMKx6Tn"
                    Issuer: "https://dev-6m9zf0-9.us.auth0.com"
            DataSources:
                Lambda:
                    GetEntriesDataSource:
                        FunctionArn: arn:aws:lambda:ap-southeast-1:481757869368:function:main_CS2P_BASE_GetEntries
                    GetEntryByIdDataSource:
                        FunctionArn: !GetAtt GetEntryByIdFunction.Arn
            Functions:
                getEntries:
                    Runtime:
                        Name: APPSYNC_JS
                        Version: "1.0.0"
                    DataSource: GetEntriesDataSource
                    CodeUri: ./gql/getEntries.js
                getEntryById:
                    Runtime:
                        Name: APPSYNC_JS
                        Version: "1.0.0"
                    DataSource: GetEntryByIdDataSource
                    CodeUri: ./gql/getEntryById.js
            Resolvers:
                Query:
                    getEntries:
                        Runtime:
                            Name: APPSYNC_JS
                            Version: "1.0.0"
                        Pipeline:
                            - getEntries
                    getEntryById:
                        Runtime:
                            Name: APPSYNC_JS
                            Version: "1.0.0"
                        Pipeline:
                            - getEntryById

